/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ro_bmocanu_javapuzzles_iq_p5_Main */

#ifndef _Included_ro_bmocanu_javapuzzles_iq_p5_Main
#define _Included_ro_bmocanu_javapuzzles_iq_p5_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ro_bmocanu_javapuzzles_iq_p5_Main
 * Method:    changeToRisk
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ro_bmocanu_javapuzzles_iq_p5_Main_changeToRisk
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
